### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by c1xx** [swagkarna/Telegram_User_Number_Finder#1]
Hi,

how to get in contact with you?

**Comment by swagkarna** [comment]
Contact me on github

**Comment by c1xx** [comment]
I would, but I don't see any option / possibility to contact you

**Comment by swagkarna** [comment]
why do you want to contact me

**Comment by c1xx** [comment]
I need your experience / skills

**Comment by swagkarna** [comment]
For what

**Comment by swagkarna** [comment]
Why you need my skills

**Comment by c1xx** [comment]
https://github.com/swagkarna/Spotify-Account-Creator-Bot#information

**Comment by swagkarna** [comment]
Explain in detail

**Comment by c1xx** [comment]
Can we have a talk outside here?

**Comment by swagkarna** [comment]
What purpose

**Comment by swagkarna** [comment]
What you want from me

**Comment by c1xx** [comment]
I don't want to talk about it in public.

**Comment by swagkarna** [comment]
If you want to say anything comment here i will delete after few minutes

**Comment by c1xx** [comment]
I search for a "streaming bot" solution.

**Comment by swagkarna** [comment]
For spotify?

**Comment by c1xx** [comment]
yes

**Comment by swagkarna** [comment]
If i have time i will think about it good bye...
