### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by s02x** [swagkarna/Telegram_User_Number_Finder#2]
Traceback (most recent call last):
  File "TG_User_Finder.py", line 4, in <module>
    from telethon import TelegramClient, events, sync
ModuleNotFoundError: No module named 'telethon'

**Comment by swagkarna** [comment]
**Use this command to install module.pip3 install telethon**

**Comment by cagdasb** [comment]
Hello, I'm having output of "Number: +1123456789 Error" at each line. 
I want to extract phone:userid:username list by using that script. If the number have telegram, output is being NULL. 
How can I fix this?
